import { ReactNode, useEffect, useMemo, useRef, useState } from 'react';
import './ui.css';

export type StatusKind = 'success' | 'failure' | 'progress' | 'review' | 'pending' | 'skipped';
const statusLabels: Record<StatusKind, string> = { success: '성공', failure: '실패', progress: '진행 중', review: '검토 대기', pending: '대기', skipped: '건너뜀' };
export const statusIcons: Record<string, string> = { success: '✓', failure: '×', progress: '●', review: '♙', pending: '○', skipped: '⊘' };
export function StatusBadge({ status, label }: { status: StatusKind; label?: string }) { return <span className={`status-badge status-${status}`}><span aria-hidden="true">{statusIcons[status]}</span>{label || statusLabels[status]}</span>; }

export type Classification = '가능' | '조건부' | '불가' | '정보 부족' | '판단 보류';
export function ClassificationScale({ value, label = '개발 가능성' }: { value?: Classification; label?: string }) { const choices: Classification[] = ['가능', '조건부', '불가', '정보 부족']; return <div className="classification"><span className="classification-label">{label}</span><div className="classification-options" role="group" aria-label={label}>{choices.map((choice) => <span key={choice} className={`${choice === value ? 'selected' : ''} ${choice === '정보 부족' || choice === '판단 보류' ? 'uncertain' : ''}`} aria-current={choice === value ? 'true' : undefined}>{choice}</span>)}</div>{value === '판단 보류' && <span className="classification-hold" aria-current="true">판단 보류</span>}</div>; }
export function ConfidenceMeter({ choiceConfidence, noulProbability }: { choiceConfidence?: number; noulProbability?: number }) { return <div className="confidence-list">{choiceConfidence !== undefined && <ConfidenceValue label="Choice confidence" value={choiceConfidence} />}{noulProbability !== undefined && <ConfidenceValue label="Noul 확률" value={noulProbability} />}</div>; }
function ConfidenceValue({ label, value }: { label: string; value: number }) { const pct = Math.max(0, Math.min(100, value * 100)); return <div className="confidence-value"><span>{label}</span><span className="confidence-track" role="meter" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(pct)}><i style={{ width: `${pct}%` }} /></span><span className="mono">{pct.toFixed(0)}%</span></div>; }
export function EvidenceLink({ children, location, onClick }: { children: ReactNode; location: string; onClick?: () => void }) { return <button type="button" className="evidence-link" aria-label={`${location} 근거 열기`} onClick={onClick}><span>{children}</span><span className="evidence-location">{location}</span></button>; }
export function IdChip({ id }: { id: string }) { const [copied, setCopied] = useState(false); return <button type="button" className="id-chip mono" title="ID 복사" onClick={async () => { try { await navigator.clipboard.writeText(id); setCopied(true); window.setTimeout(() => setCopied(false), 1400); } catch { setCopied(false); } }}><span>{id}</span><span aria-live="polite">{copied ? '복사됨' : '복사'}</span></button>; }
export function EmptyState({ title, children }: { title: string; children?: ReactNode }) { return <div className="state-panel empty-state"><span aria-hidden="true">◇</span><h2>{title}</h2>{children && <p>{children}</p>}</div>; }
export function ErrorState({ title = '문제가 발생했습니다', children, onRetry }: { title?: string; children?: ReactNode; onRetry?: () => void }) { return <div className="state-panel error-state" role="alert"><span aria-hidden="true">!</span><h2>{title}</h2>{children && <p>{children}</p>}{onRetry && <Button onClick={onRetry}>다시 시도</Button>}</div>; }
export function LoadingState({ label = '불러오는 중' }: { label?: string }) { return <div className="loading-state" role="status"><span className="spinner" aria-hidden="true" />{label}</div>; }
export function Button({ children, variant = 'primary', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'plain' }) { return <button {...props} className={`ui-button ${variant} ${props.className || ''}`}>{children}</button>; }
export function Tabs({ tabs, value, onChange }: { tabs: { id: string; label: string }[]; value: string; onChange: (id: string) => void }) { return <div className="ui-tabs" role="tablist">{tabs.map((tab) => <button key={tab.id} type="button" role="tab" aria-selected={value === tab.id} className={value === tab.id ? 'active' : ''} onClick={() => onChange(tab.id)}>{tab.label}</button>)}</div>; }
export function Modal({ open, title, onClose, children }: { open: boolean; title: string; onClose: () => void; children: ReactNode }) { return <Overlay open={open} title={title} onClose={onClose} className="modal-panel">{children}</Overlay>; }
export function Drawer({ open, title, onClose, children }: { open: boolean; title: string; onClose: () => void; children: ReactNode }) { return <Overlay open={open} title={title} onClose={onClose} className="drawer-panel">{children}</Overlay>; }
function Overlay({ open, title, onClose, children, className }: { open: boolean; title: string; onClose: () => void; children: ReactNode; className: string }) { const ref = useRef<HTMLDivElement>(null); useEffect(() => { if (!open) return; const previous = document.activeElement as HTMLElement | null; const panel = ref.current; const focusables = () => panel?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),textarea:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])'); focusables()?.[0]?.focus(); const keydown = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key === 'Tab') { const nodes = Array.from(focusables() || []); if (!nodes.length) { event.preventDefault(); return; } const first = nodes[0]; const last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; document.addEventListener('keydown', keydown); return () => { document.removeEventListener('keydown', keydown); previous?.focus(); }; }, [open, onClose]); if (!open) return null; return <div className="overlay-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section ref={ref} className={`overlay-panel ${className}`} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1}><header><h2>{title}</h2><Button variant="plain" aria-label="닫기" onClick={onClose}>×</Button></header><div className="overlay-content">{children}</div></section></div>; }
export function Toast({ message, onClose }: { message: string; onClose: () => void }) { useEffect(() => { if (!message) return; const timer = window.setTimeout(onClose, 4000); return () => window.clearTimeout(timer); }, [message, onClose]); return message ? <div className="toast" role="status"><span>{message}</span><button type="button" aria-label="알림 닫기" onClick={onClose}>×</button></div> : null; }
type Column<T> = { key: keyof T; label: string; render?: (row: T) => ReactNode };
export function DataTable<T extends object>({ columns, rows, getRowKey, caption }: { columns: Column<T>[]; rows: T[]; getRowKey: (row: T) => string; caption: string }) { const [sortKey, setSortKey] = useState<keyof T | null>(null); const [ascending, setAscending] = useState(true); const sorted = useMemo(() => !sortKey ? rows : [...rows].sort((a, b) => String(a[sortKey] ?? '').localeCompare(String(b[sortKey] ?? ''), 'ko') * (ascending ? 1 : -1)), [rows, sortKey, ascending]); return <div className="table-scroll" tabIndex={0} aria-label="표, 좌우 화살표 키로 이동"><table><caption>{caption}</caption><thead><tr>{columns.map((column) => <th key={String(column.key)} scope="col" aria-sort={sortKey === column.key ? (ascending ? 'ascending' : 'descending') : undefined}><button type="button" onClick={() => { setAscending(sortKey === column.key ? !ascending : true); setSortKey(column.key); }}>{column.label}<span aria-hidden="true">{sortKey === column.key ? ascending ? ' ↑' : ' ↓' : ' ↕'}</span></button></th>)}</tr></thead><tbody>{sorted.map((row) => <tr key={getRowKey(row)}>{columns.map((column) => <td key={String(column.key)}>{column.render ? column.render(row) : String(row[column.key] ?? '—')}</td>)}</tr>)}</tbody></table></div>; }
export function Filters({ children, onReset }: { children: ReactNode; onReset?: () => void }) { return <form className="filters" onSubmit={(event) => event.preventDefault()}><div>{children}</div>{onReset && <Button type="reset" variant="plain" onClick={onReset}>초기화</Button>}</form>; }
