import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ApiError } from '../api/client';
import { requestApi } from '../api/requests';
import { actorLabels, observeApi, playbackPosition, statusIcons, type Flow, type Playback, type RequestItem, type StepDetail, type Topology } from '../api/observe';
import {getStatusLabel} from '../components/statusLabels';
import './observatory/observatory.css';

type Run = {id:string;status:string;created_at?:string};
const statusClass=(s:string)=>`obs-status obs-${s}`;
export function Observatory(){
 const [params]=useSearchParams(); const [requests,setRequests]=useState<RequestItem[]>([]),[requestId,setRequestId]=useState(params.get('request_id')||''),[runs,setRuns]=useState<Run[]>([]),[runId,setRunId]=useState(params.get('run_id')||''),[flow,setFlow]=useState<Flow|null>(null),[playback,setPlayback]=useState<Playback|null>(null),[topology,setTopology]=useState<Topology|null>(null),[tab,setTab]=useState<'flow'|'business'|'service'>('flow'),[detail,setDetail]=useState<StepDetail|null>(null),[error,setError]=useState(''),[stream,setStream]=useState('연결 대기'),[playing,setPlaying]=useState(false),[elapsed,setElapsed]=useState(0),[speed,setSpeed]=useState(1),[zoom,setZoom]=useState(1);
 useEffect(()=>{void observeApi.requests().then(x=>{setRequests(x.items);if(!requestId&&x.items[0])setRequestId(x.items[0].id)}).catch(e=>setError((e as ApiError).message))},[]);
 useEffect(()=>{if(!requestId)return;void observeApi.runs(requestId).then(x=>{setRuns(x.runs);if(!runId&&x.active_run_id)setRunId(x.active_run_id)}).catch(e=>setError((e as ApiError).message))},[requestId]);
 useEffect(()=>{if(!runId)return;let live=true;Promise.all([observeApi.flow(runId),observeApi.playback(runId)]).then(([f,p])=>{if(live){setFlow(f);setPlayback(p);setElapsed(0);setPlaying(false)}}).catch(e=>setError((e as ApiError).message));return()=>{live=false}},[runId]);
 useEffect(()=>{if(!flow?.live||!requestId)return;let live=true;const source=new EventSource('/api/events/stream',{withCredentials:true});source.onopen=()=>live&&setStream('연결됨');source.onerror=()=>live&&setStream('재연결 중');source.addEventListener('run.step',(event:Event)=>{try{const data=JSON.parse((event as MessageEvent).data);if(data.request_id===requestId&&(!data.run_id||data.run_id===runId))void observeApi.flow(runId).then(next=>live&&setFlow(next))}catch{/* ignore malformed transient event */}});return()=>{live=false;source.close()}},[flow?.live,requestId,runId]);
 useEffect(()=>{if(tab==='flow'||!requestId)return;let live=true;observeApi.topology(requestId,tab).then(x=>live&&setTopology(x)).catch(e=>setError((e as ApiError).message));return()=>{live=false}},[tab,requestId]);
 useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>setElapsed(t=>t+250*speed),250);return()=>window.clearInterval(timer)},[playing,speed]);
 const ids=useMemo(()=>flow?.nodes.map(n=>n.id)||[],[flow]);const position=playbackPosition(playback?.events||[],elapsed,ids);const eventTimes=(playback?.events||[]).map(e=>Date.parse(e.at||'')).filter(Number.isFinite);const maxTime=eventTimes.length?Math.max(...eventTimes)-Math.min(...eventTimes):Math.max(0,...(flow?.nodes.map(n=>Date.parse(n.ended_at||'')-Date.parse(n.started_at||''))||[]));
 useEffect(()=>{if(position.failed)setPlaying(false)},[position.failed]);
 const nodeState=(id:string,status:string)=>playing||elapsed>0?(position.active.has(id)?'running':ids.indexOf(id)<=position.reached?status:'pending'):status;
 async function openStep(id:string){try{setDetail(await observeApi.step(id))}catch(e){setError((e as ApiError).message)}}
 async function reanalyze(){if(!requestId||!window.confirm('현재 입력 revision으로 새 실행을 시작할까요? 재생은 기록 조회만 수행합니다.'))return;try{const current=await requestApi.detail(requestId);const result=await requestApi.reanalyze(requestId,current.request.revision_number||current.revisions.length);const history=await observeApi.runs(requestId);setRuns(history.runs);setRunId(result.run_id);setError('')}catch(e){setError((e as ApiError).message)}}
 return <section className="observatory"><header className="obs-header"><div><p className="eyebrow">JEV TRIAGE · TRACE / PLAYBACK</p><h1>실행 관찰</h1><p>실제 저장된 실행 단계와 업무·서비스 관계를 조회합니다.</p></div><div className="obs-selectors"><label>요청<select aria-label="요청 선택" value={requestId} onChange={e=>{setRequestId(e.target.value);setRunId('')}}>{requests.map(r=><option value={r.id} key={r.id}>{r.id} · {getStatusLabel(r.status)}</option>)}</select></label><label>실행<select aria-label="실행 선택" value={runId} onChange={e=>setRunId(e.target.value)}>{runs.map(r=><option value={r.id} key={r.id}>{r.id} · {getStatusLabel(r.status)}</option>)}</select></label></div></header>
 {error&&<p role="alert" className="obs-error">{error}</p>}{!requests.length&&<p className="obs-empty">관찰 가능한 요청이 없습니다.</p>}
 {flow&&<><nav className="obs-tabs" aria-label="관찰 화면">{(['flow','business','service'] as const).map((x,i)=><button key={x} aria-pressed={tab===x} onClick={()=>setTab(x)}>{['실행 Flow','업무 Topology','서비스 Topology'][i]}</button>)}</nav><p className="obs-explainer">{tab==='flow'?'한 실행 안에서 단계 순서, 분기와 재시도를 봅니다.':tab==='business'?'요청, 배정 업무, 담당 조직과 선행 관계를 봅니다.':'실행 단계에서 호출된 서비스별 횟수와 오류를 봅니다.'} · {flow.live?<strong>실시간 실행 · SSE {stream}</strong>:<strong>과거 재생</strong>}</p>
 {tab==='flow'?<><div className="obs-controls"><button onClick={()=>{setElapsed(0);setPlaying(false)}}>처음부터</button><button onClick={()=>setPlaying(!playing)}>{playing?'일시정지':'재생'}</button><label>속도<select aria-label="재생 속도" value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[.5,1,2,4].map(s=><option key={s} value={s}>{s}×</option>)}</select></label><input aria-label="재생 구간" type="range" min="0" max={Math.max(maxTime,1000)} value={Math.min(elapsed,Math.max(maxTime,1000))} onChange={e=>{setElapsed(Number(e.target.value));setPlaying(false)}}/><button onClick={()=>{setElapsed(Number.MAX_SAFE_INTEGER);setPlaying(false)}}>전체 결과</button><button onClick={()=>setZoom(Math.max(.6,zoom-.1))}>−</button><button onClick={()=>setZoom(1)}>전체 보기</button><button onClick={()=>setZoom(Math.min(1.5,zoom+.1))}>＋</button></div><div className="obs-flow" style={{'--obs-zoom':zoom} as React.CSSProperties}>{flow.nodes.map(n=>{const state=nodeState(n.id,n.status);return <button key={n.id} className={`obs-node ${statusClass(state)}`} onClick={()=>n.id.startsWith('review:')?setDetail(n as StepDetail):void openStep(n.id)}><span className="obs-actor">{actorLabels[n.actor_kind||'']||actorLabels[n.kind]||n.kind}</span><strong>{n.name||n.kind}</strong><span>{statusIcons[state]||'○'} {getStatusLabel(state)}</span>{n.attempt&&<small>재시도 {n.attempt}</small>}{(n.predecessor_ids?.length||0)>1&&<small>병렬 {n.predecessor_ids!.length}</small>}</button>})}{flow.nodes.filter(n=>n.kind==='human'||n.status==='waiting_human').map(n=><span key={`wait${n.id}`} className="obs-wait">사람 대기 압축 · 실제 {Math.round((n.duration_ms||0)/1000)}초</span>)}</div><div className="obs-links"><Link to={`/judgment-map?run_id=${encodeURIComponent(runId)}`}>같은 실행의 판단 맵 보기</Link><Link to={`/learning?run_id=${encodeURIComponent(runId)}`}>규칙 학습에서 보기</Link></div><div className="obs-replay-note">재생은 저장 기록만 읽습니다. <button type="button" onClick={()=>void reanalyze()}>새 실행으로 다시 처리</button></div></>:<div className="obs-topology">{(topology?.nodes||topology?.services||[]).map((n,i)=><article key={String(n.id||n.name||i)} data-node-id={n.id?String(n.id):undefined} data-node-type={n.type?String(n.type):undefined}><strong>{String(n.name||n.title||n.type||'서비스')}</strong><span>{String(n.status||`${n.calls||0}회 · 오류 ${n.errors||0}`)}</span></article>)}{!((topology?.nodes||topology?.services||[]).length)&&<p>저장된 관계가 없습니다.</p>}{(topology?.edges||[]).length>0&&<ul className="obs-edges" aria-label="저장된 관계">{(topology?.edges||[]).map((e,i)=><li key={i} data-edge-from={String(e.from)} data-edge-to={String(e.to)} data-edge-kind={String(e.kind)} data-edge-role={e.role?String(e.role):undefined}>{String(e.from)} —{String(e.kind)}{e.role?` (${String(e.role)})`:''}→ {String(e.to)}</li>)}</ul>}</div>}
 <output className="obs-final">최종 실행 상태: {playback?.final_result ? getStatusLabel(playback.final_result) : ''}</output></>}
 {detail&&<aside className="obs-drawer" role="dialog" aria-label="Trace 상세"><button onClick={()=>setDetail(null)}>닫기</button><p className="eyebrow">TRACE · {detail.id}</p><h2>{detail.name||detail.kind}</h2><p>{String(actorLabels[detail.actor_kind||'']||detail.actor_kind||'')} · {String(detail.status ? getStatusLabel(detail.status) : '')}</p><p>실행 {String(detail.run_id||'')} · 설정 v{String(detail.config_version||'')}</p><p>시작 {String(detail.started_at||'—')} · 종료 {String(detail.ended_at||'진행 중')}</p>{Array.isArray(detail.rule_applications)&&detail.rule_applications.length>0&&<section aria-label="규칙 적용"><h3>적용된 규칙</h3><table><thead><tr><th>규칙</th><th>효과</th><th>결과</th><th>변경 전</th><th>변경 후</th><th>Config</th></tr></thead><tbody>{detail.rule_applications.map((a:any)=><tr key={a.rule_version}><td>{a.rule_version}</td><td>{a.effect}</td><td>{a.outcome}</td><td><code>{JSON.stringify(a.before)}</code></td><td><code>{JSON.stringify(a.after)}</code></td><td>{(a.config_versions||[]).map((v:number)=><span key={v}>v{v} </span>)}</td></tr>)}</tbody></table><p><Link to={`/judgment-map?node=${encodeURIComponent(detail.id)}&run_id=${encodeURIComponent(String(detail.run_id||runId))}`}>판단 맵에서 단계 보기</Link> · {detail.rule_applications.map((a:any)=><Link key={a.rule_id} to={`/learning?rule_id=${encodeURIComponent(a.rule_id)}`}>{a.rule_id} 규칙 학습</Link>)}</p></section>}<pre>{JSON.stringify({input:detail.input_summary,output:detail.output_summary,judgment:detail.judgment,review_history:detail.review_history,source_links:detail.source_links},null,2)}</pre>{Array.isArray(detail.source_links)&&detail.source_links.map((s:any)=><a key={s.id} href={s.url}>{s.label||s.id}</a>)}</aside>}</section>
}
