import { NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { useSession } from '../state/session';
import { ChatWidget } from '../components/ChatWidget';
import { Button } from '../components';
import { apiFetch } from '../api/client';
import { roleLabel as roleName } from '../components/statusLabels';
import { Policy } from '../pages/Policy';
import { Main } from '../pages/Main';
import { Review } from '../pages/Review';
import { Tasks } from '../pages/Tasks';
import { JudgmentMap } from '../pages/JudgmentMap';
import { Monitoring } from '../pages/Monitoring';
import { Observatory } from '../pages/Observatory';
import { Learning } from '../pages/Learning';
const items = [['/', '요청 접수'], ['/review', '검토 대기'], ['/tasks', '업무'], ['/observatory', '실행 관찰'], ['/judgment-map', '판단 맵'], ['/learning', '규칙 학습'], ['/monitoring', '모니터링'], ['/policy', '정책']] as const;
function roleLabel(roles: string[]) { return roles.map(roleName).join(' · '); }
export function AppShell() { const { user } = useSession(); const navigate = useNavigate(); const location = useLocation(); return <div className="layout"><aside className="app-sidebar"><div className="brand">Jev <span>Triage</span></div><nav aria-label="주 메뉴">{items.map(([to, label]) => <NavLink key={to} to={to} end={to === '/'}>{label}</NavLink>)}</nav><div className="sidebar-user"><strong>{user?.name || user?.id}</strong><span>{roleLabel(user?.roles || [])}</span><Button variant="plain" onClick={async () => { try { await apiFetch('/api/auth/logout', { method: 'POST' }); } catch { /* session refresh below handles absent logout endpoint */ } window.dispatchEvent(new CustomEvent('auth:unauthorized')); }}>로그아웃</Button></div></aside><div className="app-main"><header className="topbar"><span>의사결정 지원</span><div className="topbar-account"><span>{user?.name || user?.id} · {roleLabel(user?.roles || [])}</span>{user?.mode && <span className={`environment-badge mode-${user.mode}`}>{user.mode}</span>}<Button variant="plain" onClick={async () => { try { await apiFetch('/api/auth/logout', { method: 'POST' }); } catch { /* clear local session on logout */ } window.dispatchEvent(new CustomEvent('auth:unauthorized')); }}>로그아웃</Button></div></header><main><Routes>{items.map(([to, label]) => to === '/' ? <Route key={to} path={to} element={<Main />} /> : to === '/policy' ? <Route key={to} path={to} element={<Policy canEdit={user?.roles.includes('policy_editor')} />} /> : to === '/review' ? <Route key={to} path={to} element={<Review />} /> : to === '/tasks' ? <Route key={to} path={to} element={<Tasks />} /> : to === '/judgment-map' ? <Route key={to} path={to} element={<JudgmentMap />} /> : to === '/observatory' ? <Route key={to} path={to} element={<Observatory />} /> : to === '/monitoring' ? <Route key={to} path={to} element={<Monitoring />} /> : to === '/learning' ? <Route key={to} path={to} element={<Learning roles={user?.roles || []} />} /> : <Route key={to} path={to} element={<section><p className="eyebrow">JEV TRIAGE</p><h1>{label}</h1><div className="empty"><div className="mark" aria-hidden="true">◇</div><h2>화면 준비 중</h2><p>이 화면은 기능 연결 단계에서 제공됩니다.</p></div></section>} />)}<Route path="*" element={<section><h1>페이지를 찾을 수 없습니다</h1></section>} /></Routes></main></div><ChatWidget onSend={(message) => { if (location.pathname === '/') window.dispatchEvent(new CustomEvent('chat:request', { detail: message })); else { sessionStorage.setItem('chat:request', message); navigate('/'); } }} /></div>; }
